### ISSUE TITLE
SummerBatch to work with Unity 4.01

### ISSUE THREAD

**Issue by teeohdeedee** [SummerBatch/SummerBatch#10]
If our application components are referencing Unity 4.01, it causes an issue for SummerBatch integration which is looking for version 3.5 for things like IUnityContainer and SingletonRegistration.

**Comment by SummerBatchTeam** [comment]
Hi, there is no plan to support a new version of Unity yet. 
We are currently in the process of providing a version of SummerBatch for .Net core and unfortunately, Unity is not available on that platform. The future of Unity in SummerBatch has not been decided yet as it can't be used as a cross platform solution.
