### ISSUE TITLE
SqlException when multiple jobs start at once

### ISSUE THREAD

**Issue by Kalle12345** [SummerBatch/SummerBatch#16]
Hi !
In our environment we need to run two jobs in parallel.
I do get a SQL Exception.
System.Data.SqlClient.SqlException: 'Transaction (Process ID 55) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.'

I think it's also related to 
https://jira.spring.io/browse/BATCH-2147

**Comment by doshinam** [comment]
Hi,
A fix for this issue is available with v 1.1.13 RELEASE
Please note an update to the database schema is required for this version
