### ISSUE TITLE
Default ConnectionStringSettings registration missing in the sample

### ISSUE THREAD

**Issue by FatihSahin** [SummerBatch/SummerBatch#3]
We enabled job repo persistence support in SummerBatch. However, we needed to supply a ConnectionStringSettings instance to the container like this in MyFirstBatchUnityLoader.cs inside your sample application. Otherwise , DbJobRepositoryFactory can not be resolved due to missing connection string parameter. Something is probably missing from LoadConfiguration in UnityLoader base class. Can you validate the issue?

```
    public override void LoadArtifacts(IUnityContainer container)
    {
        //Connection string
        var writerConnectionstring = ConfigurationManager.ConnectionStrings["Default"];

        container.RegisterInstance<ConnectionStringSettings>("Default", writerConnectionstring)
        ...
    }
```

**Comment by SummerBatchTeam** [comment]
Hi,

Can you please check that you actually configured a connection to your database, named "Default" ? This part is explained in the [getting started guide](http://www.bluage.com/docs/summerbatch/refguide/gettingstarted.xhtml) -- see the **Database access configuration** paragraph.

Best regards,

**Comment by FatihSahin** [comment]
Yes, Default connection is added to config. Persistence tables are in the same database that step writer uses. Problem is inside UnityLoader.cs, 

```
        injectionMembers[0] = new InjectionProperty("ConnectionStringSettings",
                new ResolvedParameter<ConnectionStringSettings>("Default"));
```

This member expects a registration to the container with a name Default and a type of ConnectionStringSettings, which is not provided anywhere.

In my first comment, line below is added to workaround this problem.

```
       container.RegisterInstance<ConnectionStringSettings>("Default", writerConnectionstring);
```

However, this feels like a hack.

**Comment by SummerBatchTeam** [comment]
You are right, the connection strings are not automatically registered in the Unity context as of now. We will look into providing automatic registration in the UnityLoader in the future.

**Comment by erik75269** [comment]
Thanks for your advice. The sample project is updated in the repository. 
You can also check the documentation in the [getting started guide for summerbatch](https://www.bluage.com/site_docs/summerbatch/docs/v_1-26/site/getting_started_summerbatch/getting_started.html). -- see the Unity configuration paragraph.

Best Regard
