### ISSUE TITLE
SortTasklet - Unstable Sort vs Stable Sort

### ISSUE THREAD

**Issue by teeohdeedee** [SummerBatch/SummerBatch#7]
We are currently modernizing a legacy JCL/COBOL application and using SummerBatch.  Through our batch testing we have discovered that the SummerBatch sorting functionality does not match the legacy functionality.  While the outputted file does sort correctly by the supplied SortCard attribute information, we were still seeing differences.  It appeared that the legacy sorting was retaining the original file sort orders better.
 
After further investigation into the SummerBatch source code, we found that the code is doing what is called an “unstable sort”, where the legacy code was doing a “stable sort”.  The specific code in question can be found in class  **Summer.Batch.Extra.Sort.Sorter**, in both methods **SortAndSave()** and **InMemorySort()**.
 
The following snippet of code is performing the unstable sort in those methods:
```
// Sort the records
records.Sort(Comparer);
```
 
The [List<T>.Sort Method (IComparer<T>) ](https://msdn.microsoft.com/en-us/library/234b841s(v=vs.110).aspx)is being used.  If you follow the link to the MSDN documentation you will find the following in the “Remarks” section: 
“_This implementation performs an **unstable sort**; that is, if two elements are equal, their order might not be preserved. In contrast, a stable sort preserves the order of elements that are equal._”
 
Using this information we ran some tests in which we replaced the Sort() method with LINQ’s OrderBy() method, which performs a “stable sort”.  These tests produced the expected same sort order as the legacy sorting.
 
The following snippet of code was used to replace the example snippet above:
```
var listStableOrdered = records.OrderBy(x => x, Comparer).ToList();
records.Clear();
records.AddRange(listStableOrdered);
```
 
The [Enumerable.OrderBy<TSource, TKey> Method (IEnumerable<TSource>, Func<TSource, TKey>, IComparer<TKey>)](https://msdn.microsoft.com/en-us/library/bb549422(v=vs.110).aspx) is being used in this case.  If you follow this MSDN link, you will find the following in the “Remarks” section:
_“This method performs a **stable sort**; that is, if the keys of two elements are equal, the order of the elements is preserved. In contrast, an unstable sort does not preserve the order of elements that have the same key.”_

If an unstable sort was the intention of the SortTasklet, I think the functionality should be expanded to indicate if a stable sort should be performed instead.

Thanks,
Todd

**Comment by pkubryk** [comment]
Hi Todd, 
Thank you for your feedback.
We started working on the integration of your suggested implementation of the stable sort. We are currently looking at the impact on the sort of large files that requires doing intermediate sorts and merge the results. We target to release a new version by mid-february.

Regards,
Pierre

**Comment by SummerBatchTeam** [comment]
Hi Todd, Pierre

The Pull Request was merged. Release 1.1.4 was published.

Best regards,
The Summer Batch Team
